services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./quize
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRETKEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - BREVO_LOGIN=${BREVO_LOGIN}
      - BREVO_KEY=${BREVO_KEY}
    depends_on:
      - mysql-db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend

volumes:
  mysql_data: